services:
  # Backend API Service
  - type: web
    name: inventory-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        fromService:
          type: web
          name: inventory-frontend
          property: host
    healthCheckPath: /api/inventory/getcategories

  # Frontend Static Service  
  - type: web
    name: inventory-frontend
    env: static
    buildCommand: echo "Static frontend - no build required"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /css/*
        name: Content-Type
        value: text/css
      - path: /js/*
        name: Content-Type
        value: application/javascript
      - path: /pages/*
        name: Content-Type
        value: text/html
